//
//  ImageScrollView.swift
//  BlockSet
//
//  Created by Jakub on 11/03/2019.
//  Copyright © 2019 Jakub. All rights reserved.
//

import UIKit

class ImageScrollView: UIScrollView, UIScrollViewDelegate {

    var Problem: BlockProblem
    var Shapes: [CAShapeLayer] = []
    var Paths: [UIBezierPath] = []
    var MaxPossibleForceShape = 0

    var zoomView: UIImageView!

    lazy var zoomingTap: UITapGestureRecognizer = {
        let zoomingTap = UITapGestureRecognizer(target: self, action: #selector(handleZoomingTap(_:)))
        zoomingTap.numberOfTapsRequired = 2
        return zoomingTap
    }()

    lazy var mainSegment: UISegmentedControl = setUpSegmentedControl(elements: ["Cancel", "Submit"], yOffset: 60)

    override init(frame: CGRect) {
        self.Problem = BlockProblem()

        super.init(frame: frame)

        self.showsVerticalScrollIndicator = false
        self.showsHorizontalScrollIndicator = false
        self.decelerationRate = UIScrollView.DecelerationRate.fast
        self.delegate = self


        // AUTO GENERATED BY: ssvgparser.py
        for ShC in AutoGen.FromSVG.ShapesCoords {
            let Shape = CAShapeLayer()
            Shapes.append(Shape)
            let Path = UIBezierPath()
            Path.move(to: CGPoint(x: ShC[0].0, y: ShC[0].1))
            for Point in ShC.dropFirst() {
                Path.addLine(to: CGPoint(x: Point.0, y: Point.1))
            }
            Path.close()
            Paths.append(Path)
        }
        // END
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    override func layoutSubviews() {
        super.layoutSubviews()

        self.centerImage()
    }

    //MARK: - Configure scrollView to display new image.
    func display(_ image: UIImage) {
        // clear the previous image
        zoomView?.removeFromSuperview()
        zoomView = nil
        // make a new UIImageView for the new image
        zoomView = UIImageView(image: image)
        self.addSubview(zoomView)

        mainSegment.addTarget(self, action: #selector(ImageScrollView.mainSegmentedControlHandler(_:)), for: .valueChanged)
        superview?.addSubview(mainSegment)

        self.configureFor(image.size)

        // AUTO GENERATED BY: ssvgparser.py
        let lineDashPatterns: [NSNumber]?  = [5, 3, 3, 2]
        for (Sh, P) in zip(Shapes, Paths) {
            zoomView.layer.addSublayer(Sh)
            Sh.opacity = 0
            Sh.lineWidth = 2
            Sh.lineJoin = CAShapeLayerLineJoin.miter
            Sh.strokeColor = Defs.RedStroke.cgColor
            Sh.lineDashPattern = lineDashPatterns
            Sh.fillColor = Defs.RedFill.cgColor
            Sh.path = P.cgPath
        }
        // END
    }

    func setUpSegmentedControl(elements: [String], yOffset: CGFloat, isHidden: Bool = false) -> UISegmentedControl {
        let control = UISegmentedControl(items: elements)
        control.layer.borderColor = Defs.DarkRed.cgColor
        control.tintColor = Defs.DarkRed
        control.backgroundColor = Defs.White
        control.frame = CGRect(x: frame.minX + 10, y: frame.maxY - yOffset,
                               width: frame.maxX - 20, height: 40)
        control.isHidden = isHidden
        control.layer.cornerRadius = 15.0
        control.layer.borderWidth = 1.0
        control.layer.masksToBounds = true
        control.isMomentary = true

        return control
    }

    func configureFor(_ imageSize: CGSize) {
        self.contentSize = imageSize
        self.setMaxMinZoomScaleForCurrentBounds()
        self.zoomScale = self.minimumZoomScale
        //Enable zoom tap
        self.zoomView.addGestureRecognizer(self.zoomingTap)
        self.zoomView.isUserInteractionEnabled = true
    }

    func setMaxMinZoomScaleForCurrentBounds() {
        let boundsSize = self.bounds.size
        let imageSize = zoomView.bounds.size

        // calculate minimumZoomscale
        let xScale =  boundsSize.width  / imageSize.width
        let yScale = boundsSize.height / imageSize.height
        let minScale = min(xScale, yScale)
        self.maximumZoomScale = 5.0
        self.minimumZoomScale = minScale
    }

    func centerImage() {
        // center the zoom view as it becomes smaller than the size of the screen
        let boundsSize = self.bounds.size
        var frameToCenter = zoomView?.frame ?? CGRect.zero

        // center horizontally
        if frameToCenter.size.width < boundsSize.width {
            frameToCenter.origin.x = (boundsSize.width - frameToCenter.size.width)/2
        }
        else {
            frameToCenter.origin.x = 0
        }
        // center vertically
        if frameToCenter.size.height < boundsSize.height {
            frameToCenter.origin.y = (boundsSize.height - frameToCenter.size.height)/2
        }
        else {
            frameToCenter.origin.y = 0
        }

        zoomView?.frame = frameToCenter
    }

    //MARK: - UIScrollView Delegate Methods.
    func viewForZooming(in scrollView: UIScrollView) -> UIView? {
        return self.zoomView
    }

    func scrollViewDidZoom(_ scrollView: UIScrollView) {
        self.centerImage()
    }

    @objc func handleZoomingTap(_ sender: UITapGestureRecognizer) {
        let location = sender.location(in: sender.view)
        self.zoom(to: location, animated: true)
    }

    func zoom(to point: CGPoint, animated: Bool) {
        let currentScale = self.zoomScale
        let minScale = self.minimumZoomScale
        let maxScale = self.maximumZoomScale

        if (minScale == maxScale && minScale > 1) {
            return;
        }
        let toScale = maxScale
        let finalScale = (currentScale == minScale) ? toScale : minScale
        let zoomRect = self.zoomRect(for: finalScale, withCenter: point)
        self.zoom(to: zoomRect, animated: animated)
    }

    // The center should be in the imageView's coordinates
    func zoomRect(for scale: CGFloat, withCenter center: CGPoint) -> CGRect {
        var zoomRect = CGRect.zero
        let bounds = self.bounds

        // the zoom rect is in the content view's coordinates.
        //At a zoom scale of 1.0, it would be the size of the imageScrollView's bounds.
        //As the zoom scale decreases, so more content is visible, the size of the rect grows.
        zoomRect.size.width = bounds.size.width / scale
        zoomRect.size.height = bounds.size.height / scale

        // choose an origin so as to get the right center.
        zoomRect.origin.x = center.x - (zoomRect.size.width / 2.0)
        zoomRect.origin.y = center.y - (zoomRect.size.height / 2.0)

        return zoomRect
    }

    //MARK: - Handle Tap and Zoom.
    override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
        let touch = touches.first
        let point = touch!.location(in: self.zoomView)
        for (i, sh) in Shapes.enumerated() {
            if sh.path!.contains(point) {
                if touch!.force == touch?.maximumPossibleForce {
                    self.MaxPossibleForceShape = i
                    showSetSpecial()
                    sh.opacity = 0.5
                    Problem.add(hold: i)
                } else {
                    if (sh.opacity == 0) {
                        Problem.add(hold: i)
                        sh.opacity = 0.5
                    } else {
                        Problem.remove(hold: i)
                        sh.opacity = 0
                    }
                }
            }
        }
    }

    // MARK: - Show submit alert and text field observer.
    @objc func alertTextFieldDidChange(field: UITextField){
        let vc = findViewController()
        let alertController:UIAlertController = vc?.presentedViewController as! UIAlertController;
        let textField :UITextField  = alertController.textFields![0];
        let addAction: UIAlertAction = alertController.actions[1];
        addAction.isEnabled = (textField.text?.count)! >= 5;

    }

    func showSubmit() {
        var textField: UITextField?
        // create alertController
        let alertController = UIAlertController(title: "Submit a problem", message: "", preferredStyle: .alert)
        alertController.view.tintColor = Defs.RedStroke

        alertController.addTextField { (pTextField) in
            pTextField.placeholder = "name or descriptioin"
            pTextField.clearButtonMode = .whileEditing
            pTextField.borderStyle = .none
            pTextField.addTarget(self, action: #selector(self.alertTextFieldDidChange(field:)), for: UIControl.Event.editingChanged)
            textField = pTextField
        }
        alertController.addAction(UIAlertAction(title: "Cancel", style: .cancel, handler: { (pAction) in
            alertController.dismiss(animated: true, completion: nil)
        }))
        let okAction = UIAlertAction(title: "OK", style: .default, handler: { (pAction) in
            let problemName = textField?.text ?? ""
            self.Problem.serialize(shapes: &self.Shapes, name: problemName)
            alertController.dismiss(animated: true, completion: nil)
        })
        okAction.isEnabled = false
        alertController.addAction(okAction)
        // show alert controller
        let vc = findViewController()
        vc?.present(alertController, animated: true, completion: nil)
    }

    func showSetSpecial() {
        let Shape = Shapes[MaxPossibleForceShape]
        let alertController = UIAlertController(title: "Set special:", message: "", preferredStyle: .alert)
        alertController.view.tintColor = Defs.RedStroke

        let begin = UIAlertAction(title: "Begin", style: UIAlertAction.Style.default) {
            UIAlertAction in
            Shape.strokeColor = Defs.GreenStroke.cgColor
            Shape.fillColor = Defs.GreenFill.cgColor
        }
        let end = UIAlertAction(title: "End", style: UIAlertAction.Style.default) {
            UIAlertAction in
            Shape.strokeColor = Defs.BlueStroke.cgColor
            Shape.fillColor = Defs.BlueFill.cgColor
        }
        let feet = UIAlertAction(title: "Feet only", style: UIAlertAction.Style.default) {
            UIAlertAction in
            Shape.strokeColor = Defs.YellowStroke.cgColor
            Shape.fillColor = Defs.YellowFill.cgColor
        }
        let normal = UIAlertAction(title: "Normal", style: UIAlertAction.Style.default) {
            UIAlertAction in
            Shape.strokeColor = Defs.RedStroke.cgColor
            Shape.fillColor = Defs.RedFill.cgColor
        }
        let cancel = UIAlertAction(title: "Cancel", style: UIAlertAction.Style.cancel) {
            UIAlertAction in
        }
        // Add the actions
        alertController.addAction(begin)
        alertController.addAction(end)
        alertController.addAction(feet)
        alertController.addAction(normal)
        alertController.addAction(cancel)

        let vc = findViewController()
        vc?.present(alertController, animated: true, completion: nil)
    }

    //MARK: - Handle main segmented control.
    @objc func mainSegmentedControlHandler(_ sender: UISegmentedControl) {
        switch sender.selectedSegmentIndex {
        case 0:
            Problem.clean(shapes: &Shapes)
            break
        case 1:
            showSubmit()
            break
        default:
            break
        }
    }
}

extension UIView {
    func findViewController() -> UIViewController? {
        if let nextResponder = self.next as? UIViewController {
            return nextResponder
        } else if let nextResponder = self.next as? UIView {
            return nextResponder.findViewController()
        } else {
            return nil
        }
    }
}
